export const SET_POLICY_ID = 'SET_POLICY_ID';
export const SET_CUSTOMER_ID = 'SET_CUSTOMER_ID';
export const GET_INSURANCE_DATA_REQUEST = 'GET_INSURANCE_DATA_REQUEST';
export const GET_INSURANCE_DATA_SUCCESS = 'GET_INSURANCE_DATA_SUCCESS';
export const GET_INSURANCE_DATA_FAILED = 'GET_INSURANCE_DATA_FAILED';
export const SET_INSURANCE_DATA_SELECTED_DOC = 'SET_INSURANCE_DATA_SELECTED_DOC';
export const EDIT_DETAILS = 'EDIT_DETAILS';
